#! /bin/sh
set -e

case "$1" in
	start)
		echo "staring aesdchar"
		aesdchar_load
		;;
	stop)
		echo "stopping aesdchar"
		aesdchar_unload
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

